#include <stdio.h>
#include <stdlib.h>
#include <limits.h>

typedef long long ll;

typedef struct {
    int to, next;
    ll w;
} Edge;

typedef struct {
    ll d;
    int v, k;
} HeapNode;

Edge *e;
int *head;
int ec = 0;

HeapNode *heap;
int hs = 0;

void addEdge(int u, int v, ll w) {
    e[ec].to = v;
    e[ec].w = w;
    e[ec].next = head[u];
    head[u] = ec++;
}

void push(HeapNode x) {
    int i = hs++;
    while (i > 0) {
        int p = (i - 1) / 2;
        if (heap[p].d <= x.d) break;
        heap[i] = heap[p];
        i = p;
    }
    heap[i] = x;
}

HeapNode pop() {
    HeapNode r = heap[0], x = heap[--hs];
    int i = 0;

    while (2 * i + 1 < hs) {
        int c = 2 * i + 1;
        if (c + 1 < hs && heap[c + 1].d < heap[c].d)
            c++;

        if (heap[c].d >= x.d) break;

        heap[i] = heap[c];
        i = c;
    }

    if (hs) heap[i] = x;
    return r;
}

int main() {
    int n, m, k, src, dst;
    scanf("%d %d %d %d %d", &n, &m, &k, &src, &dst);

    head = (int *)malloc((n + 1) * sizeof(int));
    e = (Edge *)malloc(m * sizeof(Edge));

    for (int i = 1; i <= n; i++)
        head[i] = -1;

    for (int i = 0; i < m; i++) {
        int u, v;
        ll w;
        scanf("%d %d %lld", &u, &v, &w);
        addEdge(u, v, w);
    }

    int S = k + 1;
    ll *dist = (ll *)malloc((n + 1) * S * sizeof(ll));

    for (int i = 0; i <= n; i++)
        for (int j = 0; j < S; j++)
            dist[i * S + j] = LLONG_MAX;

    /*
       Maximum useful states = n * (k+1).
       Allocate enough space for heap entries generated by relaxations.
    */
    heap = (HeapNode *)malloc((size_t)(2 * m * S + n * S + 10)
                              * sizeof(HeapNode));

    dist[src * S] = 0;
    push((HeapNode){0, src, 0});

    ll answer = LLONG_MAX;

    while (hs) {
        HeapNode cur = pop();

        if (cur.d != dist[cur.v * S + cur.k])
            continue;

        if (cur.v == dst) {
            answer = cur.d;
            break;
        }

        for (int i = head[cur.v]; i != -1; i = e[i].next) {
            int to = e[i].to;
            ll w = e[i].w;

            /* Option 1: pay the road cost */
            ll nd = cur.d + w;
            int id = to * S + cur.k;

            if (nd < dist[id]) {
                dist[id] = nd;
                push((HeapNode){nd, to, cur.k});
            }

            /* Option 2: use one token and make this road free */
            if (cur.k < k) {
                id = to * S + cur.k + 1;

                if (cur.d < dist[id]) {
                    dist[id] = cur.d;
                    push((HeapNode){cur.d, to, cur.k + 1});
                }
            }
        }
    }

    if (answer == LLONG_MAX)
        printf("-1\n");
    else
        printf("%lld\n", answer);

    free(head);
    free(e);
    free(dist);
    free(heap);

    return 0;
}
